"""empty message

Revision ID: 410510f88bca
Revises: 45ed97452d99
Create Date: 2020-10-07 06:06:16.049127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '410510f88bca'
down_revision = '45ed97452d99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('comment_author', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'comment_author')
    # ### end Alembic commands ###
