"""empty message

Revision ID: 7ccc783a7c7f
Revises: 410510f88bca
Create Date: 2020-10-07 06:52:32.227194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ccc783a7c7f'
down_revision = '410510f88bca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('username', sa.String(), nullable=True))
    op.drop_column('comments', 'comment_author')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('comment_author', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('comments', 'username')
    # ### end Alembic commands ###
